from __future__ import annotations
import collections.abc
import pyimgui.imgui
import typing
from . import detours
from . import inbound
__all__: list[str] = ['Dx11Inbound', 'Dx11Texture', 'Dx11Window', '_Dx11Render', '_RenderBase', 'detours', 'inbound']
class Dx11Inbound(_Dx11Render):
    def Attach(self) -> None:
        ...
    def Detach(self) -> None:
        ...
    def __init__(self, renderCallback: collections.abc.Callable | None = None) -> None:
        ...
    @property
    def isInLogic(self) -> bool:
        ...
class Dx11Texture:
    @property
    def handle(self) -> int:
        ...
    @property
    def height(self) -> int:
        ...
    @property
    def width(self) -> int:
        ...
class Dx11Window(_Dx11Render):
    ClearColor: pyimgui.imgui.ImVec4
    def CreateDeviceObjects(self) -> bool:
        ...
    def InvalidateDeviceObjects(self) -> None:
        ...
    def Serve(self) -> None:
        ...
    def __init__(self, renderCallback: collections.abc.Callable | None = None) -> None:
        ...
class _Dx11Render(_RenderBase):
    @staticmethod
    def CreateDeviceObjects() -> bool:
        ...
    @staticmethod
    def InvalidateDeviceObjects() -> None:
        ...
    def CreateTexture(self, filename: str) -> Dx11Texture:
        ...
class _RenderBase:
    renderCallback: collections.abc.Callable | None
    title: str
    def CallBeforeFrameOnce(self, arg0: collections.abc.Callable) -> None:
        ...
    def Close(self) -> None:
        ...
    def HideToTray(self) -> None:
        ...
    def RestoreFromTray(self) -> None:
        ...
    def UpdateTrayIconInfo(self, tooltip: str, iconPath: str = '') -> None:
        ...
