from __future__ import annotations
import collections.abc
import pyimgui.imgui
import typing
from . import detours
from . import inbound
__all__: list[str] = ['Dx12Inbound', 'Dx12Render', 'Dx12TextureHelper', 'Dx12Window', '_RenderBase', 'detours', 'inbound']
class Dx12Inbound(Dx12Render):
    def Attach(self) -> None:
        ...
    def Detach(self) -> None:
        ...
    def __init__(self, renderCallback: collections.abc.Callable | None = None) -> None:
        ...
    @property
    def isInLogic(self) -> bool:
        ...
class Dx12Render(_RenderBase):
    @staticmethod
    def CreateDeviceObjects() -> bool:
        ...
    @staticmethod
    def InvalidateDeviceObjects() -> None:
        ...
    @typing.overload
    def CreateTexture(self, filename: str) -> Dx12TextureHelper:
        ...
    @typing.overload
    def CreateTexture(self) -> Dx12TextureHelper:
        ...
class Dx12TextureHelper:
    def FreeTexture(self) -> None:
        ...
    def LoadTextureFromFile(self, arg0: str) -> None:
        ...
    def __bool__(self) -> bool:
        ...
    @property
    def handle(self) -> int:
        ...
    @property
    def height(self) -> int:
        ...
    @property
    def size(self) -> pyimgui.imgui.ImVec2:
        ...
    @property
    def width(self) -> int:
        ...
class Dx12Window(Dx12Render):
    ClearColor: pyimgui.imgui.ImVec4
    def Serve(self) -> None:
        ...
    def __init__(self, renderCallback: collections.abc.Callable | None = None) -> None:
        ...
class _RenderBase:
    renderCallback: collections.abc.Callable | None
    title: str
    def CallBeforeFrameOnce(self, arg0: collections.abc.Callable) -> None:
        ...
    def Close(self) -> None:
        ...
    def HideToTray(self) -> None:
        ...
    def RestoreFromTray(self) -> None:
        ...
    def UpdateTrayIconInfo(self, tooltip: str, iconPath: str = '') -> None:
        ...
