"""Generate `nylib/imguiutils/icons/fa/{solid,regular}.py` and download the
matching TTFs from the Font Awesome Free release archive.

Re-run this script to bump the pinned FA version.

Usage:
    python scripts/gen_fa_icons.py
    python scripts/gen_fa_icons.py --version 6.7.2

Network: fetches over HTTPS from raw.githubusercontent.com.
License: Font Awesome Free is SIL OFL 1.1 (fonts) + CC BY 4.0 (icons).
"""
from __future__ import annotations

import argparse
import json
import keyword
import pathlib
import re
import sys
import urllib.request

DEFAULT_VERSION = "6.7.2"
RAW = "https://raw.githubusercontent.com/FortAwesome/Font-Awesome/{ver}/{path}"
META_PATH = "metadata/icons.json"
TTF_PATHS = {
    "solid":   "webfonts/fa-solid-900.ttf",
    "regular": "webfonts/fa-regular-400.ttf",
}

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
PKG_ROOT = REPO_ROOT / "nylib" / "imguiutils" / "icons" / "fa"
RES_DIR = PKG_ROOT / "resources"

_BAD_LEAD = re.compile(r"^[^A-Za-z_]")


def _sanitise(name: str) -> str:
    s = re.sub(r"[^0-9A-Za-z]+", "_", name).strip("_").lower()
    if _BAD_LEAD.match(s) or keyword.iskeyword(s):
        s = "_" + s
    return "fa_" + s


def _fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "nylib-icon-gen"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def _write_style(style: str, version: str, entries: list[tuple[str, str]]) -> None:
    out = PKG_ROOT / f"{style}.py"
    lines: list[str] = []
    lines.append(f'"""AUTO-GENERATED by scripts/gen_fa_icons.py - DO NOT EDIT."""')
    lines.append(f"# Font Awesome {version} Free {style.capitalize()}")
    lines.append("# License: SIL OFL 1.1 (font) + CC BY 4.0 (icons)")
    lines.append("")
    seen: dict[str, str] = {}
    glyphs: list[str] = []
    for raw_name, code in entries:
        ident = _sanitise(raw_name)
        suffix = 2
        base = ident
        while ident in seen:
            ident = f"{base}_{suffix}"
            suffix += 1
        seen[ident] = code
        char = chr(int(code, 16))
        glyphs.append(char)
        lines.append(f"{ident} = {char!r}  # U+{code.upper()} {raw_name}")
    lines.append("")
    glyph_blob = "".join(glyphs)
    lines.append(f"_glyphs_ = {glyph_blob!r}")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"  wrote {out.relative_to(REPO_ROOT)}  ({len(entries)} icons)")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", default=DEFAULT_VERSION, help="FA tag (default %(default)s)")
    args = ap.parse_args()
    ver = args.version

    PKG_ROOT.mkdir(parents=True, exist_ok=True)
    RES_DIR.mkdir(parents=True, exist_ok=True)
    (PKG_ROOT / "__init__.py").touch()  # placeholder; hand-written later
    (RES_DIR / ".gitkeep").write_text("")

    print(f"[fa-gen] fetching metadata for Font Awesome {ver}")
    meta_url = RAW.format(ver=ver, path=META_PATH)
    icons = json.loads(_fetch(meta_url))

    # FA also ships glyphs mapped onto ASCII codepoints ("a", "0", "@", ...). We skip those:
    # merging them into the atlas would override the default font's letters/digits.
    MIN_CODEPOINT = 0x2000

    per_style: dict[str, list[tuple[str, str]]] = {"solid": [], "regular": []}
    skipped = 0
    for name, info in sorted(icons.items()):
        code = info.get("unicode")
        styles = info.get("styles", [])
        if not code:
            continue
        if int(code, 16) < MIN_CODEPOINT:
            skipped += 1
            continue
        for s in styles:
            if s in per_style:
                per_style[s].append((name, code))
    if skipped:
        print(f"  skipped {skipped} icons mapped to ASCII/low codepoints")

    for style, entries in per_style.items():
        _write_style(style, ver, entries)

    for style, sub in TTF_PATHS.items():
        url = RAW.format(ver=ver, path=sub)
        dest = RES_DIR / pathlib.PurePosixPath(sub).name
        print(f"[fa-gen] downloading {sub}")
        dest.write_bytes(_fetch(url))
        print(f"  wrote {dest.relative_to(REPO_ROOT)}  ({dest.stat().st_size:,} bytes)")

    print(f"[fa-gen] done. FA {ver}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
